//This file is generated by Bash-script

int GAPS_APT_SetFieldFunction(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs)
{
	int Type = pInputs->EMField_Type;
	if (-1 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Discrete;
	}
	else if(0 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Uniform;
	}
	else if(1 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Tokamak;
	}
	else if(2 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_TokamakRE;
	}
	else if(3 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_RadNonUniform;
	}
	else if(4 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EarthDipole;
	}
	else if(5 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EOscillator;
	}
	else if(6 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_MagMirrorChain;
	}
	else if(7 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EMbenchmark;
	}
	else if(8 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_hairer5_1;
	}
	else if(9 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_hairerquad;
	}
	else if(10 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_hairerrandom;
	}
	else if(11 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EM_non_case1;
	}
	else if(12 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EM_int_case1;
	}
	else if(13 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EM_N_ed_case1;
	}
	else if(14 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EM_N_ox_case1;
	}
	else if(15 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EM_N_rg_case1;
	}
	else if(16 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EMhairerEquadBnc3;
	}
	else if(17 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EM_I_type1_case1;
	}
	else if(18 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EM_I_type1_case2;
	}
	else if(19 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Ksymng;
	}
	else if(20 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Henon;
	}
	else if(21 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Henon_ConstantB;
	}
	else if(22 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Henon_B;
	}
	else if(23 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_uncompact;
	}
	else if(24 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Henon_Heiles;
	}
	else
	{
		fprintf(stderr,"ERROR: In function GAPS_APT_SetFieldFunction: Electromagnetic field type is wrong! You input Field_Type = %ld\n",(long)Type);
	}
	return 0;
}
