//This file is generated by Bash-script

int GAPS_APT_Field_Uniform(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_Tokamak(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_TokamakRE(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_RadNonUniform(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_EarthDipole(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_EOscillator(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_MagMirrorChain(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_EMbenchmark(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_Henon_Heiles_FlexEB(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_Henon_Heiles_FlexEB_quarterB(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_Henon_Heiles_AsymB(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_Henon_Heiles_AsymmB(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_Henon_Heiles_AsymmB_3D(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_Hairer51_FlexBE(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_Zjs_E_drift(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Field_HairerRandomWalk_flexEB(double *pTensor,double *pSpaceTime4,int Order,Gaps_IO_InputsContainer *pInputs);
