//This file is generated by Bash-script

int GAPS_APT_SetFieldFunction(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs)
{
	int Type = pInputs->EMField_Type;
	if (-1 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Discrete;
	}
	else if(0 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Uniform;
	}
	else if(1 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Tokamak;
	}
	else if(2 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_TokamakRE;
	}
	else if(3 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_RadNonUniform;
	}
	else if(4 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EarthDipole;
	}
	else if(5 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EOscillator;
	}
	else if(6 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_MagMirrorChain;
	}
	else if(7 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_EMbenchmark;
	}
	else if(8 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Henon_Heiles_FlexEB;
	}
	else if(9 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Henon_Heiles_FlexEB_quarterB;
	}
	else if(10 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Henon_Heiles_AsymB;
	}
	else if(11 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Henon_Heiles_AsymmB;
	}
	else if(12 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Henon_Heiles_AsymmB_3D;
	}
	else if(13 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Hairer51_FlexBE;
	}
	else if(14 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_Zjs_E_drift;
	}
	else if(15 == Type)
	{
		pPtc->FieldFunc = GAPS_APT_Field_HairerRandomWalk_flexEB;
	}
	else
	{
		fprintf(stderr,"ERROR: In function GAPS_APT_SetFieldFunction: Electromagnetic field type is wrong! You input Field_Type = %ld\n",(long)Type);
	}
	return 0;
}
