//This file is generated by Bash-script

int GAPS_APT_ExtForce_RadLarmor(double *pField,Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_ExtForce_GCElecCollision(double *pField,Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_ExtForce_GCElecBremsstrahlung(double *pField,Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
