//This file is generated by Bash-script

int GAPS_APT_SetParticlePosition(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs)
{
	double *pT=GAPS_APT_GetT1(pPtc);
	*pT= 0.;
	if(!(strcmp(pInputs->Init_X_Type,"Constant")))
	{
		GAPS_APT_SetParticlePosition_Constant(pPtc,pInputs);
	}
	else if(!(strcmp(pInputs->Init_X_Type,"Cuboid")))
	{
		GAPS_APT_SetParticlePosition_Cuboid(pPtc,pInputs);
	}
	else if(!(strcmp(pInputs->Init_X_Type,"Cylinder")))
	{
		GAPS_APT_SetParticlePosition_Cylinder(pPtc,pInputs);
	}
	else if(!(strcmp(pInputs->Init_X_Type,"Torus")))
	{
		GAPS_APT_SetParticlePosition_Torus(pPtc,pInputs);
	}
	else if(!(strcmp(pInputs->Init_X_Type,"ParabolicTorus")))
	{
		GAPS_APT_SetParticlePosition_ParabolicTorus(pPtc,pInputs);
	}
	else
	{
		fprintf(stderr,"ERROR: In function GAPS_APT_SetParticlePosition: Initial position type is wrong! You input Init_X_Type = %s\n",pInputs->Init_X_Type);
	}
	return 0;
}

int GAPS_APT_SetParticleMomentum(Gaps_APT_Particle *pPtc, Gaps_IO_InputsContainer *pInputs)
{
	double *pGamma=GAPS_APT_GetGamma1(pPtc);
	double *pP=GAPS_APT_GetP3(pPtc);
	if(!(strcmp(pInputs->Init_P_Type,"Constant")))
	{
		GAPS_APT_SetParticleMomentum_Constant(pPtc,pInputs);
	}
	else if(!(strcmp(pInputs->Init_P_Type,"Maxwell")))
	{
		GAPS_APT_SetParticleMomentum_Maxwell(pPtc,pInputs);
	}
	else if(!(strcmp(pInputs->Init_P_Type,"Gyrocenter")))
	{
		GAPS_APT_SetParticleMomentum_Gyrocenter(pPtc,pInputs);
	}
	else if(!(strcmp(pInputs->Init_P_Type,"Cuboid")))
	{
		GAPS_APT_SetParticleMomentum_Cuboid(pPtc,pInputs);
	}
	else
	{
		fprintf(stderr,"ERROR: In function GAPS_APT_SetParticleMomentum: Initial momentum type is wrong! You input Init_P_Type = %s\n",pInputs->Init_P_Type);
	}
	*pGamma=sqrt(1.+pP[0]*pP[0]+pP[1]*pP[1]+pP[2]*pP[2]);
	return 0;
}

int GAPS_APT_SetParticleAcceleration(Gaps_APT_Particle *pPtc, Gaps_IO_InputsContainer *pInputs)
{
	if(!(strcmp(pInputs->Init_Aclr_Type,"Constant")))
	{
		GAPS_APT_SetParticleAcceleration_Constant(pPtc,pInputs);
	}
	else
	{
		fprintf(stderr,"ERROR: In function GAPS_APT_SetParticleAcceleration: Initial acceleration type is wrong! You input Init_Aclr_Type = %s\n",pInputs->Init_Aclr_Type);
	}
	return 0;
}
