//This file is generated by Bash-script

int GAPS_APT_SetParticlePosition_Constant(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_SetParticlePosition_Cuboid(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_SetParticlePosition_Cylinder(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_SetParticlePosition_Torus(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_SetParticlePosition_ParabolicTorus(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_SetParticleMomentum_Constant(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_SetParticleMomentum_Maxwell(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_SetParticleMomentum_Gyrocenter(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_SetParticleMomentum_Cuboid(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_SetParticleAcceleration_Constant(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
