//This file is generated by Bash-script

int GAPS_APT_Pusher_RVPA_Cay3D(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Pusher_LCCSA_SymEuler(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Pusher_RCSA_SymEuler(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Pusher_RVPA_Exp3D(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Pusher_RungeKutta(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Pusher_RNCSA_4D(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Pusher_RECSA_GF4D(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Pusher_LCCSA_IMP(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Pusher_Regular_Boris(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Pusher_Onehalf_Boris(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Pusher_CSA_SymEuler(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
int GAPS_APT_Pusher_CSA_imEuler(Gaps_APT_Particle *pPtc,Gaps_IO_InputsContainer *pInputs);
