// This file is generated by Bash-script.
// This file contains generated macro definitions needed by the particle structure.
#define GAPS_APT_CONST_PTC_DATA_LEN 30
 
//#define GAPS_APT_CONST_PTC_SAVEDATA_LEN 10
 
//Function Macros
//Description of function names: 
//	GET_[Parameter name]_[Length of this parameter]
 
/* 0	1	2		3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25		26		27		28		29*/
/* q	m	\tau	t	x	y	z	r	px	py	pz	phi	Ax	Ay	Az	R	Px	Py	Pz	Ex	Ey	Ez	Bx	By	Bz	Aclrx	Aclry	Aclrz	Ework	die*/

#define GAPS_APT_GetCharge1(Ptc) (((Ptc)->data))/*! Return Charge */
#define GAPS_APT_GetMass1(Ptc) ((((Ptc)->data)+1))/*! Return Mass */
#define GAPS_APT_GetS1(Ptc) (((Ptc)->data)+2)/*! Return Pointer of Evolution Parameter*/
#define GAPS_APT_GetX4(Ptc) (((Ptc)->data)+3)/*! Return Pointer of Spacetime*/
#define GAPS_APT_GetP4(Ptc) (((Ptc)->data)+7)/*! Return Pointer of Mechanical Momentum*/
#define GAPS_APT_GetA4(Ptc) (((Ptc)->data)+11)/*! Return Pointer of Velocity*/
#define GAPS_APT_GetCanP4(Ptc) (((Ptc)->data)+15)/*! Return Pointer of Canonical Momentum*/

#define GAPS_APT_GetT1(Ptc) (((Ptc)->data)+3)/*! Return Pointer of Spacetime*/
#define GAPS_APT_GetX3(Ptc) (((Ptc)->data)+4)/*! Return Pointer of position*/
#define GAPS_APT_GetP3(Ptc) (((Ptc)->data)+8)/*! Return Pointer of Mechanical Momentum*/
#define GAPS_APT_GetA3(Ptc) (((Ptc)->data)+12)/*! Return Pointer of Velocity*/
#define GAPS_APT_GetGamma1(Ptc) (((Ptc)->data)+7)/*! Return Pointer of Mechanical Momentum*/
#define GAPS_APT_GetCanP3(Ptc) (((Ptc)->data)+16)/*! Return Pointer of 3 Canonical Momentum*/
#define GAPS_APT_GetE3(Ptc) (((Ptc)->data)+19)/*! Return Pointer of Electric Field */
#define GAPS_APT_GetB3(Ptc) (((Ptc)->data)+22)/*! Return Pointer of Magnetic Field */
#define GAPS_APT_GetAclr3(Ptc) (((Ptc)->data)+25)/*! Return Pointer of Acceleration*/
#define GAPS_APT_GetEwork1(Ptc) (((Ptc)->data)+28)/*! Return Pointer of Acceleration*/
#define GAPS_APT_GetDie1(Ptc) (((Ptc)->data)+29)/*! Return Pointer of Acceleration*/


// from data
#define GAPS_APT_GetCharge_FromData(data)	(*(data))/*! Return Charge */
#define GAPS_APT_GetMass_FromData(data)		(*((data)+1))/*! Return Mass */
#define GAPS_APT_GetS1_FromData(data)		((data)+2)/*! Return Pointer of Evolution Parameter*/
#define GAPS_APT_GetX4_FromData(data)		((data)+3)/*! Return Pointer of Spacetime*/
#define GAPS_APT_GetP4_FromData(data)		((data)+7)/*! Return Pointer of Mechanical Momentum*/
#define GAPS_APT_GetA4_FromData(data)		((data)+11)/*! Return Pointer of Velocity*/
#define GAPS_APT_GetCanP4_FromData(data)	((data)+15)/*! Return Pointer of Canonical Momentum*/

#define GAPS_APT_GetT1_FromData(data)		((data)+3)/*! Return Pointer of Spacetime*/
#define GAPS_APT_GetX3_FromData(data)		((data)+4)/*! Return Pointer of position*/
#define GAPS_APT_GetP3_FromData(data)		((data)+8)/*! Return Pointer of Mechanical Momentum*/
#define GAPS_APT_GetA3_FromData(data)		((data)+12)/*! Return Pointer of Velocity*/
#define GAPS_APT_GetGamma1_FromData(data)	((data)+7)/*! Return Pointer of Mechanical Momentum*/
#define GAPS_APT_GetCanP3_FromData(data)	((data)+16)/*! Return Pointer of 3 Canonical Momentum*/
#define GAPS_APT_GetE3_FromData(data)		((data)+19)/*! Return Pointer of Electric Field */
#define GAPS_APT_GetB3_FromData(data)		((data)+22)/*! Return Pointer of Magnetic Field */
#define GAPS_APT_GetAclr3_FromData(data)	((data)+25)/*! Return Pointer of Acceleration*/
#define GAPS_APT_GetEwork1_FromData(data)	((data)+28)/*! Return Pointer of Acceleration*/
#define GAPS_APT_GetDie_FromData(Ptc)		((data)+29)/*! Return Pointer of Acceleration*/
